### ISSUE TITLE
是否可以生成随机范围内的日期的，如果可以就更好了。

### ISSUE THREAD

**Issue by bambooj** [GongDexing/DataGenerator#1]

**Comment by GongDexing** [comment]
这个想法很好，目前可以采用拼接pool方式实现
><date>$pool{year}-$pool{month}-$pool{date}</date>

在配置文件定义
> pool.year=2010,2011,2012,2013
> pool.month=01,02
> pool.date=01,02,03

这里问题就是每个月的天数是不同的，因此可能会产生些不合理的日期，比如20120230，后面有空会把随机日期作为内置变量加进去，实现代码也很简单
```java
public class DateHelper {
    private static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static Random rand = new Random();
    public static String randomDate(int recentYears) {
        LocalDate date = LocalDate.now();
        return date.minusDays(rand.nextInt(recentYears*365)).format(formatter);
    }
}
```

**Comment by GongDexing** [comment]
已经增加了内置随机日期变量
> $date{startDate,endDate,format}

具体用法
> <date>$date{2017-02-01,now,yyyy-MM-dd}</date>

表示按照 **yyyy-MM-dd** 随机产生一个日期，并且日期在[2017-02-01,当前日期] 范围内容
